# Cloud service catalog workbook generator
# Generates a Microsoft Excel workbook with two sheets:
# 1) Service Naming Matrix
# 2) Unique Services & Features

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

PROVIDERS = [
    "AWS",
    "Azure",
    "GCP",
    "IBM Cloud",
    "OCI",
    "Alibaba Cloud",
    "Tencent Cloud",
    "DigitalOcean",
    "OVHcloud",
    "Linode (Akamai)",
    "Vultr",
    "Rackspace Technology",
    "Kamatera",
    "IONOS Cloud",
    "Cloudways",
    "Scaleway",
    "Hetzner Cloud",
    "Huawei Cloud",
    "Salesforce",
    "SAP SE",
    "VMware Cloud",
    "Fujitsu Cloud",
    "CenturyLink (Lumen)",
    "NTT Global Data Centers",
    "Red Hat OpenShift",
]

SERVICE_MATRIX = [
    [
        "Virtual Machines / Compute Instances",
        "Amazon EC2",
        "Azure Virtual Machines",
        "Compute Engine VM Instances",
        "Virtual Servers",
        "OCI Compute / Bare Metal",
        "Alibaba ECS",
        "Tencent CVM",
        "DigitalOcean Droplets",
        "OVHcloud Instances",
        "Linode Compute Instances",
        "Vultr Cloud Compute",
        "Rackspace Cloud Servers",
        "Kamatera Cloud Servers",
        "IONOS Cloud VMs",
        "Cloudways Managed Servers",
        "Scaleway Instances",
        "Hetzner Cloud Servers",
        "Huawei ECS",
        "Salesforce Platform / Heroku Dynos",
        "SAP Business Technology Platform / SAP HANA Cloud",
        "VMware Cloud VM Instances",
        "Fujitsu Compute Service / K5",
        "CenturyLink / Lumen Cloud Servers",
        "NTT Managed Compute Services",
        "Red Hat OpenShift Container Platform",
    ],
    [
        "Object Storage",
        "Amazon S3",
        "Azure Blob Storage",
        "Google Cloud Storage",
        "IBM Cloud Object Storage",
        "OCI Object Storage",
        "Alibaba OSS",
        "Tencent COS",
        "DigitalOcean Spaces",
        "OVHcloud Object Storage",
        "Linode Object Storage",
        "Vultr Object Storage",
        "Rackspace Cloud Files",
        "Kamatera Storage",
        "IONOS S3 Object Storage",
        "Cloudways Object Storage / CDN",
        "Scaleway Object Storage",
        "Hetzner Object Storage",
        "Huawei OBS",
        "Salesforce Data Cloud / Files",
        "SAP HANA Data Lake / Object Storage",
        "VMware Cloud Storage Services",
        "Fujitsu Object Storage",
        "CenturyLink Object Storage",
        "NTT Data Storage Services",
        "Red Hat OpenShift Persistent Storage",
    ],
    [
        "Block Storage",
        "Amazon EBS",
        "Azure Managed Disks",
        "Persistent Disks",
        "IBM Cloud Block Storage",
        "OCI Block Volumes",
        "Alibaba ESSD / Block Storage",
        "Tencent CBS",
        "DigitalOcean Volumes",
        "OVHcloud Block Storage",
        "Linode Block Storage",
        "Vultr Block Storage",
        "Rackspace Cloud Block Storage",
        "Kamatera Block Storage",
        "IONOS Cloud Storage",
        "Cloudways Block Storage",
        "Scaleway Block Storage",
        "Hetzner Cloud Volumes",
        "Huawei EVS",
        "Salesforce Files / Data Storage",
        "SAP HANA Persistent Storage",
        "VMware vSAN / vSphere Storage",
        "Fujitsu Storage Services",
        "CenturyLink Block Storage",
        "NTT Storage Services",
        "Red Hat OpenShift Persistent Volumes",
    ],
    [
        "Relational Database",
        "Amazon RDS",
        "Azure Database for PostgreSQL/MySQL/SQL",
        "Cloud SQL",
        "IBM Db2 on Cloud / Cloud Databases",
        "OCI Autonomous Database / MySQL / PostgreSQL",
        "Alibaba RDS",
        "Tencent Cloud DB",
        "DigitalOcean Managed Databases",
        "OVHcloud Managed Databases",
        "Linode Managed Databases",
        "Vultr Managed Databases",
        "Rackspace Managed Databases",
        "Kamatera Managed Databases",
        "IONOS Managed Database",
        "Cloudways Managed Database",
        "Scaleway Managed Databases",
        "Hetzner Managed Databases",
        "Huawei RDS",
        "Salesforce Data Cloud / CRM Data",
        "SAP HANA Cloud / SAP ASE / SAP MaxDB",
        "VMware Cloud Database Services",
        "Fujitsu Database Services",
        "CenturyLink Managed Databases",
        "NTT Managed DB Services",
        "Red Hat OpenShift PostgreSQL / MySQL Operators",
    ],
    [
        "NoSQL Database",
        "Amazon DynamoDB",
        "Azure Cosmos DB",
        "Cloud Firestore / Bigtable / Spanner",
        "IBM Cloud Databases for MongoDB / Redis / Cassandra",
        "OCI NoSQL Database / Autonomous JSON Database",
        "Alibaba Table Store / MongoDB",
        "Tencent Cloud NoSQL DB",
        "DigitalOcean Managed MongoDB",
        "OVHcloud MongoDB / Redis",
        "Linode Managed MongoDB",
        "Vultr Managed Databases",
        "Rackspace NoSQL Services",
        "Kamatera Managed DBs",
        "IONOS Managed Databases",
        "Cloudways Managed Database",
        "Scaleway Managed Databases",
        "Hetzner Managed MongoDB",
        "Huawei GaussDB / MongoDB",
        "Salesforce Platform Data / Heroku Postgres",
        "SAP HANA / SAP HANA Cloud",
        "VMware Cloud Data Services",
        "Fujitsu Cloud NoSQL Services",
        "CenturyLink NoSQL / Managed Data",
        "NTT Managed Cloud Data Services",
        "Red Hat OpenShift Data Services",
    ],
    [
        "Serverless Compute",
        "AWS Lambda",
        "Azure Functions",
        "Cloud Functions",
        "IBM Cloud Functions",
        "OCI Functions",
        "Alibaba Function Compute",
        "Tencent SCF",
        "DigitalOcean Functions",
        "OVHcloud Serverless",
        "Linode Serverless",
        "Vultr Serverless",
        "Rackspace Serverless",
        "Kamatera Function Hosting",
        "IONOS Serverless",
        "Cloudways Serverless / App Platform",
        "Scaleway Functions",
        "Hetzner Cloud Functions",
        "Huawei FunctionGraph",
        "Salesforce Apex / Platform Events",
        "SAP SAP Cloud Platform Functions",
        "VMware Cloud Services / Tanzu",
        "Fujitsu Functions / Serverless",
        "CenturyLink Serverless Workloads",
        "NTT Managed Serverless",
        "Red Hat OpenShift Serverless",
    ],
    [
        "Kubernetes / Container Platform",
        "Amazon EKS",
        "Azure AKS",
        "Google Kubernetes Engine (GKE)",
        "IBM Cloud Kubernetes Service",
        "OCI Kubernetes Engine (OKE)",
        "Alibaba ACK",
        "Tencent TKE",
        "DigitalOcean Kubernetes",
        "OVHcloud Managed Kubernetes",
        "Linode Kubernetes Engine",
        "Vultr Kubernetes",
        "Rackspace Kubernetes",
        "Kamatera Kubernetes",
        "IONOS Managed Kubernetes",
        "Cloudways Kubernetes",
        "Scaleway Kapsule",
        "Hetzner Cloud Kubernetes",
        "Huawei CCE",
        "Salesforce Heroku / App Platform",
        "SAP BTP Kyma / OpenShift",
        "VMware Tanzu Kubernetes Grid",
        "Fujitsu Container Services",
        "CenturyLink Managed Kubernetes",
        "NTT Kubernetes Services",
        "Red Hat OpenShift",
    ],
    [
        "Load Balancer",
        "Amazon ELB / ALB / NLB",
        "Azure Load Balancer",
        "Cloud Load Balancing",
        "IBM Cloud Load Balancer",
        "OCI Load Balancing",
        "Alibaba SLB",
        "Tencent CLB",
        "DigitalOcean Load Balancers",
        "OVHcloud Load Balancer",
        "Linode NodeBalancers",
        "Vultr Load Balancers",
        "Rackspace Load Balancers",
        "Kamatera Load Balancers",
        "IONOS Load Balancer",
        "Cloudways Load Balancer",
        "Scaleway Load Balancers",
        "Hetzner Load Balancers",
        "Huawei ELB",
        "Salesforce Platform Load Balancing",
        "SAP BTP Load Balancer",
        "VMware NSX Load Balancing",
        "Fujitsu Load Balancers",
        "CenturyLink Load Balancers",
        "NTT Load Balancing",
        "Red Hat OpenShift Routes / Ingress",
    ],
    [
        "DNS / Traffic Management",
        "Amazon Route 53",
        "Azure DNS",
        "Cloud DNS",
        "IBM Cloud DNS",
        "OCI DNS",
        "Alibaba DNS",
        "Tencent DNSPod",
        "DigitalOcean DNS",
        "OVHcloud DNS",
        "Linode DNS Manager",
        "Vultr DNS",
        "Rackspace Cloud DNS",
        "Kamatera DNS",
        "IONOS Domain & DNS",
        "Cloudways DNS",
        "Scaleway Domains & DNS",
        "Hetzner DNS",
        "Huawei DNS",
        "Salesforce Domain Management",
        "SAP DNS / BTP Routing",
        "VMware NSX Edge / DNS",
        "Fujitsu DNS Services",
        "CenturyLink DNS",
        "NTT DNS Services",
        "Red Hat OpenShift Routes / DNS",
    ],
    [
        "Monitoring & Logging",
        "Amazon CloudWatch / X-Ray",
        "Azure Monitor / Log Analytics",
        "Cloud Monitoring / Logging",
        "IBM Cloud Monitoring / Log Analysis",
        "OCI Monitoring / Logging",
        "Alibaba CloudMonitor",
        "Tencent Cloud Monitoring",
        "DigitalOcean Monitoring",
        "OVHcloud Logs and Monitoring",
        "Linode Monitoring",
        "Vultr Monitoring",
        "Rackspace Monitoring",
        "Kamatera Monitoring",
        "IONOS Monitoring",
        "Cloudways Monitoring",
        "Scaleway Monitoring",
        "Hetzner Monitoring",
        "Huawei Cloud Eye",
        "Salesforce Event Monitoring",
        "SAP Cloud ALM / Application Monitoring",
        "VMware Aria / vRealize",
        "Fujitsu Monitoring Services",
        "CenturyLink Monitoring",
        "NTT Monitoring Services",
        "Red Hat OpenShift Monitoring",
    ],
    [
        "Identity & Access Management",
        "AWS IAM",
        "Azure Active Directory / Entra ID",
        "Cloud IAM",
        "IBM Cloud IAM",
        "OCI IAM",
        "Alibaba RAM",
        "Tencent CAM",
        "DigitalOcean Teams / Access",
        "OVHcloud IAM",
        "Linode Account / Access",
        "Vultr Access Control",
        "Rackspace Identity Management",
        "Kamatera Access Control",
        "IONOS Identity & Access",
        "Cloudways Access Control",
        "Scaleway IAM",
        "Hetzner IAM",
        "Huawei IAM",
        "Salesforce Identity / Access",
        "SAP Identity Management",
        "VMware Identity Manager",
        "Fujitsu IAM",
        "CenturyLink Identity Services",
        "NTT Identity Services",
        "Red Hat OpenShift RBAC / SSO",
    ],
    [
        "Virtual Private Cloud / Networking",
        "Amazon VPC",
        "Azure Virtual Network",
        "VPC Network",
        "IBM Cloud VPC",
        "OCI Virtual Cloud Network",
        "Alibaba VPC",
        "Tencent VPC",
        "DigitalOcean VPC",
        "OVHcloud vRack / Private Network",
        "Linode VPC / Private Networking",
        "Vultr Private Networking",
        "Rackspace Cloud Networks",
        "Kamatera Private Networks",
        "IONOS Virtual Private Cloud",
        "Cloudways Private Networking",
        "Scaleway VPC",
        "Hetzner Cloud Network",
        "Huawei VPC",
        "Salesforce Private Connect",
        "SAP Private Connectivity",
        "VMware NSX-T / VPC",
        "Fujitsu Network Services",
        "CenturyLink Private Network",
        "NTT Private Network Solutions",
        "Red Hat OpenShift SDN / Network Policies",
    ],
    [
        "Message Queue / Event Service",
        "Amazon SQS / SNS / EventBridge",
        "Azure Service Bus / Event Grid",
        "Cloud Pub/Sub",
        "IBM MQ / Event Streams",
        "OCI Streaming / Notifications",
        "Alibaba MNS / RocketMQ",
        "Tencent CMQ / CKafka",
        "DigitalOcean Message Queues",
        "OVHcloud Messaging",
        "Linode Events / Queues",
        "Vultr Queues / Eventing",
        "Rackspace Messaging",
        "Kamatera Message Queues",
        "IONOS Messaging",
        "Cloudways Queueing",
        "Scaleway Messaging",
        "Hetzner Messaging",
        "Huawei DMS / Kafka",
        "Salesforce Platform Events / Pub/Sub",
        "SAP Event Mesh / Messaging",
        "VMware Event Broker / RabbitMQ",
        "Fujitsu Messaging Services",
        "CenturyLink Messaging",
        "NTT Messaging Services",
        "Red Hat OpenShift Messaging / Eventing",
    ],
    [
        "Artificial Intelligence / ML",
        "Amazon SageMaker / Bedrock",
        "Azure AI Foundry / Machine Learning",
        "Vertex AI / Gemini",
        "IBM Watsonx / AI Labs",
        "OCI AI / Data Science",
        "Alibaba PAI",
        "Tencent TI Platform",
        "DigitalOcean AI / ML",
        "OVHcloud AI / ML",
        "Linode AI / ML",
        "Vultr AI / ML",
        "Rackspace AI Solutions",
        "Kamatera AI Solutions",
        "IONOS AI Infrastructure",
        "Cloudways AI Hosting",
        "Scaleway AI / ML",
        "Hetzner AI Cloud",
        "Huawei ModelArts",
        "Salesforce Einstein AI",
        "SAP AI Core / Joule",
        "VMware AI / Data Services",
        "Fujitsu AI Platform",
        "CenturyLink AI / Data Services",
        "NTT AI Services",
        "Red Hat OpenShift AI / Data Science",
    ],
    [
        "Data Warehouse / Analytics",
        "Amazon Redshift",
        "Azure Synapse Analytics",
        "BigQuery",
        "IBM Db2 Warehouse / watsonx.data",
        "OCI Autonomous Data Warehouse",
        "Alibaba AnalyticDB",
        "Tencent TiDB / Big Data",
        "DigitalOcean Managed Analytics",
        "OVHcloud Big Data Services",
        "Linode Analytics",
        "Vultr Managed Analytics",
        "Rackspace Analytics",
        "Kamatera Analytics", 
        "IONOS Analytics",
        "Cloudways Analytics",
        "Scaleway Data Warehouse",
        "Hetzner Analytics",
        "Huawei AnalyticDB",
        "Salesforce Tableau / CRM Analytics",
        "SAP Datasphere / BW/4HANA",
        "VMware Data Services",
        "Fujitsu Data Analytics",
        "CenturyLink Data Analytics",
        "NTT Analytics Platforms",
        "Red Hat OpenShift Data Services",
    ],
    [
        "Website Hosting / Managed App Hosting",
        "Amazon Lightsail / Elastic Beanstalk",
        "Azure App Service / Web Apps",
        "Google App Engine / Cloud Run",
        "IBM Cloud Code Engine / Web Hosting",
        "OCI App Dev / Web Hosting",
        "Alibaba Web Hosting",
        "Tencent Cloud Web Hosting",
        "DigitalOcean App Platform",
        "OVHcloud Web Hosting",
        "Linode App Platform",
        "Vultr App Platform",
        "Rackspace Managed Hosting",
        "Kamatera Web Hosting",
        "IONOS Web Hosting / Cloud",
        "Cloudways Managed Hosting",
        "Scaleway Managed Hosting",
        "Hetzner Managed Hosting",
        "Huawei Web App Service",
        "Salesforce Heroku / App Cloud",
        "SAP BTP Web Apps / Cloud Foundry",
        "VMware Cloud Foundry / Tanzu",
        "Fujitsu Cloud Hosting",
        "CenturyLink Hosting",
        "NTT Managed Website Hosting",
        "Red Hat OpenShift App Hosting",
    ],
    [
        "CDN / Edge Delivery",
        "Amazon CloudFront",
        "Azure CDN",
        "Cloud CDN",
        "IBM Cloud CDN",
        "OCI CDN",
        "Alibaba CDN",
        "Tencent CDN",
        "DigitalOcean CDN",
        "OVHcloud CDN",
        "Linode CDN",
        "Vultr CDN",
        "Rackspace CDN",
        "Kamatera CDN",
        "IONOS CDN",
        "Cloudways CDN",
        "Scaleway CDN",
        "Hetzner CDN",
        "Huawei CDN",
        "Salesforce Edge / CDN",
        "SAP CDN / BTP Edge",
        "VMware Edge / CDN",
        "Fujitsu CDN Services",
        "CenturyLink Edge Delivery",
        "NTT CDN / Edge Services",
        "Red Hat OpenShift Edge / Ingress",
    ],
    [
        "Backup / DR",
        "Amazon Backup / Glacier",
        "Azure Backup / Site Recovery",
        "Cloud Backup / Disaster Recovery",
        "IBM Cloud Backup / Resilience",
        "OCI Backup / Disaster Recovery",
        "Alibaba Cloud Backup",
        "Tencent Cloud Backup",
        "DigitalOcean Backups",
        "OVHcloud Backup / Recovery",
        "Linode Backups",
        "Vultr Backups",
        "Rackspace Backup Services",
        "Kamatera Backup",
        "IONOS Backup",
        "Cloudways Backup",
        "Scaleway Backup",
        "Hetzner Backup",
        "Huawei Backup",
        "Salesforce Data Recovery",
        "SAP Backup / Restore",
        "VMware SRM / Veeam",
        "Fujitsu Backup Services",
        "CenturyLink Backup",
        "NTT Disaster Recovery",
        "Red Hat OpenShift Backup / Velero",
    ],
]

UNIQUE_FEATURES = [
    ("AWS", "Lambda", "Serverless", "Runs code in response to events without managing servers."),
    ("AWS", "S3 Glacier", "Storage", "Low-cost archival storage for infrequently accessed data."),
    ("AWS", "EKS Anywhere", "Kubernetes", "Runs Kubernetes on-premises and in edge environments with AWS consistency."),
    ("Azure", "Azure Functions", "Serverless", "Event-driven compute service for lightweight workloads and integrations."),
    ("Azure", "Azure Arc", "Hybrid Cloud", "Manages servers, Kubernetes, and apps across on-prem, multi-cloud, and edge."),
    ("Azure", "Azure AI Foundry", "AI", "Unified environment for building, customizing, and deploying AI workloads."),
    ("GCP", "BigQuery", "Analytics", "Serverless data warehouse optimized for large-scale analytics and SQL queries."),
    ("GCP", "Cloud Run", "Containers", "Runs containerized apps without managing infrastructure or clusters."),
    ("GCP", "Anthropic / Gemini AI integrations", "AI", "Google's AI ecosystem for model development and enterprise AI applications."),
    ("IBM Cloud", "Watsonx", "AI", "Enterprise AI and data platform for model training, governance, and deployment."),
    ("IBM Cloud", "Cloud Pak", "Hybrid Cloud", "Collection of containerized software for hybrid multicloud operations and integration."),
    ("IBM Cloud", "Virtual Private Cloud", "Networking", "Segmented private cloud networking with enterprise-grade isolation."),
    ("OCI", "Autonomous Database", "Database", "Self-driving database service that automates tuning, patching, and scaling."),
    ("OCI", "Oracle Cloud VMware Solution", "Hybrid Cloud", "Runs VMware workloads natively in Oracle's cloud environment."),
    ("OCI", "FastConnect", "Networking", "Dedicated high-bandwidth connection between enterprise data centers and OCI."),
    ("Alibaba Cloud", "ApsaraDB", "Database", "Family of managed database offerings for MySQL, PostgreSQL, and more."),
    ("Alibaba Cloud", "PolarDB", "Database", "Cloud-native relational database built for high performance and low latency."),
    ("Alibaba Cloud", "MaxCompute", "Analytics", "Large-scale data processing and analytics platform for enterprise workloads."),
    ("Tencent Cloud", "Cloud Virtual Machine (CVM)", "Compute", "Elastic compute instances designed for scalable workloads in China and global regions."),
    ("Tencent Cloud", "TencentDB", "Database", "Managed relational, NoSQL, and memory database services across major workloads."),
    ("Tencent Cloud", "COS", "Storage", "High-availability object storage for backups, media, and app data."),
    ("DigitalOcean", "App Platform", "PaaS", "Deploys web apps and background workers with simplified managed workflows."),
    ("DigitalOcean", "Managed Databases", "Database", "Quickly deploy managed PostgreSQL, MySQL, and Redis environments."),
    ("DigitalOcean", "Spaces", "Storage", "Simple object storage built for developers and static assets."),
    ("OVHcloud", "vRack", "Networking", "Private network layer that connects OVHcloud services across regions and racks."),
    ("OVHcloud", "Bare Metal Servers", "Compute", "Dedicated physical machines for high-performance workloads and custom setups."),
    ("OVHcloud", "Private Cloud", "Infrastructure", "Enterprise private cloud environment with dedicated resources and management options."),
    ("Linode (Akamai)", "Managed Databases", "Database", "Fully managed database service for PostgreSQL and MySQL with simple maintenance."),
    ("Linode (Akamai)", "NodeBalancers", "Networking", "Layer 4 load balancing for improved app availability and scaling."),
    ("Linode (Akamai)", "Akamai Connected Cloud", "Delivery", "Edge-enabled distributed cloud platform across the Akamai network."),
    ("Vultr", "Bare Metal", "Compute", "Dedicated bare-metal servers for workloads requiring full hardware control."),
    ("Vultr", "Cloud GPU", "Compute", "GPU-powered virtual machines for AI, rendering, and machine learning workloads."),
    ("Vultr", "Object Storage", "Storage", "Simple storage for backups, media, and application data."),
    ("Rackspace Technology", "Fanatical Support", "Managed Services", "Managed support model with operations assistance for cloud workloads."),
    ("Rackspace Technology", "Private Cloud", "Infrastructure", "Dedicated hosted private cloud services for regulated and enterprise workloads."),
    ("Rackspace Technology", "Managed Hosting", "Hosting", "Full-service orchestration and management of infrastructure and applications."),
    ("Kamatera", "Cloud Servers", "Compute", "Flexible VM offerings with per-hour billing and quick provisioning."),
    ("Kamatera", "Private Cloud", "Infrastructure", "Dedicated private cloud environments for secure and isolated operations."),
    ("Kamatera", "Custom Configurations", "Compute", "Highly customizable VM specs for niche performance and memory needs."),
    ("IONOS Cloud", "Cloud Server", "Compute", "IaaS compute service with flexible sizing and migration-friendly options."),
    ("IONOS Cloud", "Managed Kubernetes", "Containers", "Kubernetes service for enterprise container orchestration and application portability."),
    ("IONOS Cloud", "DCD / Domain Services", "Networking", "Domain and DNS management services for public-facing workloads."),
    ("Cloudways", "Managed Hosting Platform", "Hosting", "Fully managed hosting for WordPress, Magento, PHP apps, and Laravel workloads."),
    ("Cloudways", "1-Click App Deployment", "PaaS", "Rapid deployment for popular web stacks with managed operations."),
    ("Cloudways", "Server Monitoring", "Operations", "Built-in monitoring and performance visibility across managed servers."),
    ("Scaleway", "Kapsule", "Kubernetes", "Simplified managed Kubernetes service for container orchestration."),
    ("Scaleway", "Instances", "Compute", "Flexible virtual servers for general-purpose and specialized workloads."),
    ("Scaleway", "Bare Metal", "Compute", "Dedicated physical machines for performance-sensitive workloads."),
    ("Hetzner Cloud", "Cloud GPU", "Compute", "Affordable GPU instances suited to AI, rendering, and heavy computing tasks."),
    ("Hetzner Cloud", "Storage Boxes", "Storage", "Managed storage offerings for backup and file sharing scenarios."),
    ("Hetzner Cloud", "Volume Storage", "Storage", "High-performance block storage attached to cloud servers."),
    ("Huawei Cloud", "ModelArts", "AI", "Platform for training, deployment, and management of AI models."),
    ("Huawei Cloud", "GaussDB", "Database", "Distributed database platform optimized for enterprise and OLTP workloads."),
    ("Huawei Cloud", "CCE", "Containers", "Managed Kubernetes service for microservices and containerized applications."),
    ("Salesforce", "Einstein AI", "AI", "AI-powered analytics, recommendations, and automation across Salesforce applications."),
    ("Salesforce", "Heroku", "PaaS", "Platform for deploying apps, APIs, and dynos with streamlined developer workflows."),
    ("Salesforce", "Platform Events", "Integration", "Event-driven integration for building scalable messaging and workflows."),
    ("SAP SE", "Business Technology Platform (BTP)", "PaaS", "Unified platform for application development, integration, data, and AI services."),
    ("SAP SE", "Joule", "AI", "Embedded AI assistant for business workflows and enterprise productivity."),
    ("SAP SE", "Kyma", "Kubernetes", "Extension framework and runtime for cloud-native enterprise applications."),
    ("VMware Cloud", "Tanzu", "Containers", "Modern application platform for Kubernetes, DevSecOps, and multi-cloud deployment."),
    ("VMware Cloud", "vSphere", "Virtualization", "Hypervisor platform for enterprise virtualization and private cloud operations."),
    ("VMware Cloud", "NSX", "Networking", "Software-defined networking and security for virtualized workloads."),
    ("Fujitsu Cloud", "K5", "Infrastructure", "Enterprise cloud service with high availability and hybrid-cloud design."),
    ("Fujitsu Cloud", "Fujitsu Cloud Service", "Compute", "Managed cloud infrastructure for enterprise workloads and data-rich applications."),
    ("Fujitsu Cloud", "Hybrid Cloud Integration", "Hybrid Cloud", "Integrated cloud services for workloads across on-prem and cloud environments."),
    ("CenturyLink (Lumen)", "Edge Computing", "Edge", "Computing closer to users for latency-sensitive and distributed applications."),
    ("CenturyLink (Lumen)", "Private Cloud", "Infrastructure", "Managed private cloud for secure enterprise workloads and modernization projects."),
    ("CenturyLink (Lumen)", "Managed Hosting", "Hosting", "Hosted application and infrastructure management for businesses and regulated workloads."),
    ("NTT Global Data Centers", "Managed Data Center Cloud", "Infrastructure", "Colocation and managed cloud services with enterprise-grade global reach."),
    ("NTT Global Data Centers", "Private Cloud", "Infrastructure", "Dedicated cloud infrastructure for secure enterprise hosting and migration workloads."),
    ("NTT Global Data Centers", "Edge Services", "Edge", "Distributed compute and network services for low-latency global business operations."),
    ("Red Hat OpenShift", "OpenShift Serverless", "Serverless", "Serverless workflows built on Kubernetes-native platform services."),
    ("Red Hat OpenShift", "OpenShift AI", "AI", "AI-enabled platform for model development and deployment in enterprise container stacks."),
    ("Red Hat OpenShift", "OpenShift Pipelines", "DevOps", "CI/CD pipeline automation using Kubernetes-native best practices."),
]


def apply_header_style(ws):
    fill = PatternFill("solid", fgColor="4472C4")
    font = Font(color="FFFFFF", bold=True)
    for cell in ws[1]:
        cell.fill = fill
        cell.font = font


def set_column_widths(ws):
    for column_cells in ws.columns:
        length = max(len(str(cell.value)) if cell.value is not None else 0 for cell in column_cells)
        ws.column_dimensions[column_cells[0].column_letter].width = min(max(length + 2, 14), 30)


# Create workbook
wb = Workbook()
ws1 = wb.active
ws1.title = "Service Naming Matrix"
header = ["Common Name of the service"] + PROVIDERS
ws1.append(header)

for row in SERVICE_MATRIX:
    ws1.append(row)

apply_header_style(ws1)
set_column_widths(ws1)
ws1.freeze_panes = "A2"
ws1.auto_filter.ref = ws1.dimensions

ws2 = wb.create_sheet("Unique Services & Features")
ws2.append(["Provider", "Service / Feature Name", "Category", "Simple Description"])
for row in UNIQUE_FEATURES:
    ws2.append(list(row))
apply_header_style(ws2)
set_column_widths(ws2)
ws2.freeze_panes = "A2"
ws2.auto_filter.ref = ws2.dimensions

# Save workbook
output_path = "cloud_service_catalog.xlsx"
wb.save(output_path)
print(f"Created: {output_path}")

# CSV exports for spreadsheet compatibility and easy review
import csv

matrix_csv = "cloud_service_catalog_matrix.csv"
with open(matrix_csv, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(SERVICE_MATRIX)

unique_csv = "cloud_service_catalog_unique_features.csv"
with open(unique_csv, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["Provider", "Service / Feature Name", "Category", "Simple Description"])
    writer.writerows(UNIQUE_FEATURES)

print(f"Created: {matrix_csv}")
print(f"Created: {unique_csv}")
